### ISSUE TITLE
Error when validating the yaml file

### ISSUE THREAD

**Issue by M1cN** [chatziko/ha-google-cloud-stt#5]
Hi, i'm getting the following error message when validating the yaml file:

Package stt setup failed. Component stt cannot be merged. Expected a dict.

yaml:

```
stt:
  - platform: google_cloud_stt
    key_file: google_service_account.json
    model: command_and_search
```
